package Adebabay.Clinic_Backend;

import Adebabay.Clinic_Backend.model.*;
import Adebabay.Clinic_Backend.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.*;

@Component
public class DataInitializer implements CommandLineRunner {

    @Autowired
    private MongoTemplate mongoTemplate;

    @Autowired
    private HomeRepository homeRepository;

    @Autowired
    private AboutRepository aboutRepository;

    @Autowired
    private ServicesRepository servicesRepository;

    @Autowired
    private FooterRepository footerRepository;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Initializing data...");

        // Test MongoDB connection FIRST
        System.out.println("Checking MongoDB connection...");
        try {
            String dbName = mongoTemplate.getDb().getName();
            System.out.println("✅ MongoDB connected successfully to database: " + dbName);
        } catch (Exception e) {
            System.out.println("❌ MongoDB connection failed: " + e.getMessage());
            System.out.println("Skipping data initialization...");
            return;
        }

        // Initialize data if collections are empty
        if (homeRepository.count() == 0) {
            initializeHomeData();
            System.out.println("Home data initialized");
        } else {
            System.out.println("Home data already exists");
        }

        if (aboutRepository.count() == 0) {
            initializeAboutData();
            System.out.println("About data initialized");
        } else {
            System.out.println("About data already exists");
        }

        if (servicesRepository.count() == 0) {
            initializeServicesData();
            System.out.println("Services data initialized");
        } else {
            System.out.println("Services data already exists");
        }

        if (footerRepository.count() == 0) {
            initializeFooterData();
            System.out.println("Footer data initialized");
        } else {
            System.out.println("Footer data already exists");
        }

        System.out.println("Data initialization completed!");
    }

    private void initializeHomeData() {
        HomeContent home = new HomeContent();
        home.setId(null); // Will be auto-generated by MongoDB
        home.setHeroTitle("Welcome to HealthCare Clinic");
        home.setHeroDescription("Your trusted partner for comprehensive healthcare services with compassion and expertise.");
        home.setHeroImageUrl("/images/hero-banner.jpg");
        home.setHeroButtonText("Book Appointment");
        home.setHeroButtonLink("/contact");

        // Create features list
        List<HomeContent.Feature> features = new ArrayList<>();
        features.add(new HomeContent.Feature("24/7 Emergency", "Round-the-clock emergency services", "fa-ambulance"));
        features.add(new HomeContent.Feature("Expert Doctors", "Experienced medical professionals", "fa-user-md"));
        features.add(new HomeContent.Feature("Modern Equipment", "State-of-the-art medical technology", "fa-medkit"));
        home.setFeatures(features);

        // Create stats map
        Map<String, Integer> stats = new HashMap<>();
        stats.put("yearsExperience", 25);
        stats.put("happyPatients", 50000);
        stats.put("doctors", 50);
        stats.put("departments", 12);
        home.setStats(stats);

        home.setActive(true);
        home.setCreatedAt(LocalDateTime.now());

        homeRepository.save(home);
    }

    private void initializeAboutData() {
        AboutContent about = new AboutContent();
        about.setId(null); // Will be auto-generated by MongoDB
        about.setPageTitle("About HealthCare Clinic");
        about.setMainDescription("For over 25 years, we have been providing exceptional healthcare services to our community...");
        about.setMission("To provide compassionate, comprehensive healthcare that improves the quality of life for our patients.");
        about.setVision("To be the leading healthcare provider in the region, recognized for excellence in patient care.");
        about.setHistory("Founded in 1999 by Dr. John Smith, our clinic has grown to become a trusted healthcare provider...");

        // Create values list
        List<String> values = new ArrayList<>(Arrays.asList(
                "Patient-Centered Care",
                "Medical Excellence",
                "Compassion",
                "Integrity",
                "Teamwork"
        ));
        about.setValues(values);

        // Create team list
        List<AboutContent.TeamMember> team = new ArrayList<>();
        team.add(new AboutContent.TeamMember(
                "Dr. John Smith",
                "Cardiologist",
                "MD, FACC",
                "15 years experience in cardiology",
                "/images/doctors/dr-john-smith.jpg",
                15,
                Arrays.asList("Heart Disease", "Hypertension")
        ));
        team.add(new AboutContent.TeamMember(
                "Dr. Sarah Johnson",
                "Pediatrician",
                "MD, FAAP",
                "12 years experience in pediatrics",
                "/images/doctors/dr-sarah-johnson.jpg",
                12,
                Arrays.asList("Child Healthcare", "Vaccinations")
        ));
        about.setTeam(team);

        // Create statistics map
        Map<String, Object> stats = new HashMap<>();
        stats.put("founded", 1999);
        stats.put("patientsPerYear", 5000);
        stats.put("surgeries", 1500);
        stats.put("doctors", 50);
        stats.put("nurses", 120);
        about.setStatistics(stats);

        about.setCreatedAt(LocalDateTime.now());
        about.setUpdatedAt(LocalDateTime.now());

        aboutRepository.save(about);
    }

    private void initializeServicesData() {
        List<ClinicService> services = new ArrayList<>();
        services.add(createService("General Consultation", "Routine health checkups and consultations with our experienced doctors", "General", 50.0, 1));
        services.add(createService("Cardiology", "Heart health assessments, ECG, and specialized treatments", "Specialist", 150.0, 2));
        services.add(createService("Pediatrics", "Child healthcare, vaccinations, and growth monitoring", "Specialist", 80.0, 3));
        services.add(createService("Dental Care", "Complete dental examinations, cleaning, and treatments", "Dental", 120.0, 4));

        servicesRepository.saveAll(services);
    }

    private ClinicService createService(String name, String description, String category, double price, int order) {
        ClinicService service = new ClinicService();
        service.setId(null); // Will be auto-generated by MongoDB
        service.setName(name);
        service.setDescription(description);

        // Create short description (first 100 characters)
        String shortDesc = description.length() > 100 ? description.substring(0, 100) + "..." : description;
        service.setShortDescription(shortDesc);

        service.setCategory(category);
        service.setPrice(price);
        service.setPriceUnit("per session");
        service.setDisplayOrder(order);
        service.setIcon("fa-" + category.toLowerCase());
        service.setImageUrl("/images/services/" + name.toLowerCase().replace(" ", "-") + ".jpg");
        service.setActive(true);
        service.setFeatured(order <= 3);
        service.setEstimatedDuration(30);

        // Create benefits list
        List<String> benefits = new ArrayList<>(Arrays.asList(
                "Expert medical staff",
                "Modern equipment",
                "Personalized care",
                "Follow-up consultations"
        ));
        service.setBenefits(benefits);

        // Create procedures list
        List<String> procedures = new ArrayList<>(Arrays.asList(
                "Initial consultation",
                "Diagnostic tests",
                "Treatment plan",
                "Follow-up appointment"
        ));
        service.setProcedures(procedures);

        // Create features list
        List<String> features = new ArrayList<>(Arrays.asList(
                "Same-day appointments available",
                "Insurance accepted",
                "Multilingual staff",
                "Wheelchair accessible"
        ));
        service.setFeatures(features);

        service.setCreatedAt(LocalDateTime.now());
        service.setUpdatedAt(LocalDateTime.now());

        return service;
    }

    private void initializeFooterData() {
        Footer footer = new Footer();
        footer.setId(null); // Will be auto-generated by MongoDB
        footer.setClinicName("HealthCare Clinic");
        footer.setAddress("123 Medical Street, Health City, HC 12345");
        footer.setPhone("+1 (234) 567-8900");
        footer.setEmail("info@healthcareclinic.com");
        footer.setEmergencyContact("+1 (234) 567-8911");

        // Create quick links
        List<Footer.Link> quickLinks = new ArrayList<>();
        quickLinks.add(new Footer.Link("Home", "/", "_self"));
        quickLinks.add(new Footer.Link("About Us", "/about", "_self"));
        quickLinks.add(new Footer.Link("Services", "/services", "_self"));
        quickLinks.add(new Footer.Link("Contact", "/contact", "_self"));
        footer.setQuickLinks(quickLinks);

        // Create service links (same as quick links for now)
        footer.setServiceLinks(quickLinks);

        // Create social links
        List<Footer.SocialLink> socialLinks = new ArrayList<>();
        socialLinks.add(new Footer.SocialLink("Facebook", "https://facebook.com/healthcareclinic", "fab fa-facebook", "Facebook"));
        socialLinks.add(new Footer.SocialLink("Twitter", "https://twitter.com/healthcareclinic", "fab fa-twitter", "Twitter"));
        socialLinks.add(new Footer.SocialLink("Instagram", "https://instagram.com/healthcareclinic", "fab fa-instagram", "Instagram"));
        socialLinks.add(new Footer.SocialLink("LinkedIn", "https://linkedin.com/company/healthcareclinic", "fab fa-linkedin", "LinkedIn"));
        footer.setSocialLinks(socialLinks);

        // Create legal links
        List<Footer.Link> legalLinks = new ArrayList<>();
        legalLinks.add(new Footer.Link("Privacy Policy", "/privacy", "_self"));
        legalLinks.add(new Footer.Link("Terms of Service", "/terms", "_self"));
        legalLinks.add(new Footer.Link("Cookie Policy", "/cookies", "_self"));
        footer.setLegalLinks(legalLinks);

        footer.setCopyrightText("© 2024 HealthCare Clinic. All rights reserved.");
        footer.setDevelopedBy("HealthCare Team");
        footer.setDevelopedByLink("#");
        footer.setNewsletterEnabled(true);
        footer.setNewsletterTitle("Subscribe to Our Newsletter");
        footer.setNewsletterDescription("Get the latest health tips and clinic updates");

        footer.setCreatedAt(LocalDateTime.now());
        footer.setUpdatedAt(LocalDateTime.now());

        footerRepository.save(footer);
    }
}